spring:
  datasource:
    username: root
    password: chenZhen
    driver-class-name: com.mysql.jdbc.Driver  # 可以自动识别
    url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false