spring:
  datasource:
    username: root
    password: chenZhen
    driver-class-name: com.mysql.jdbc.Driver  # 可以自动识别
    url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false

mybatis:
  #mapper-locations: classpath:mybatis-mapper/*.xml  # mybatis的SQL文件路径
  type-aliases-package: com.cimc.entity  # 配置实体类别名

