spring:
  datasource:
    username: admin
    password: Abc_123456
    driver-class-name: com.mysql.jdbc.Driver  # 可以自动识别
    url: jdbc:mysql://192.168.20.95:8066/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml  # mybatis的SQL文件路径
  type-aliases-package: com.cimc.entity  # 配置实体类别名
  #config-location: classpath:mybatis/mybatis-config.xml  # mybatis配置文件

logging:
  level:
    com:
      cimc:
        mapper: debug