server:
  port: 8001

spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8000  # admin server的地址

management:
  endpoints:
    web:
      exposure:
        include: '*' # 打开Actuator的监控
