spring:
  datasource:
    primary:
      username: root
      password: chenZhen
      driver-class-name: com.mysql.jdbc.Driver  # 可以自动识别
      jdbc-url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    secondary:
      username: root
      password: chenZhen
      driver-class-name: com.mysql.jdbc.Driver  # 可以自动识别
      jdbc-url: jdbc:mysql://localhost:3306/springboot_demo2?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true