mysql:
  datasource:
    one:
      username: root
      password: chenZhen
      url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
    two:
      username: root
      password: chenZhen
      url: jdbc:mysql://localhost:3306/springboot_demo2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60


